package com.zjut.graduate.Service.impl;

import com.zjut.graduate.Service.AnalysisAiService;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.Map;

@Service
public class AnalysisAiServiceImpl implements AnalysisAiService {
    @Override
    public String analyzeMistake(String questionContent, String userAnswer, String correctAnswer) {
        return "AI analysis placeholder: connect Spring AI ChatClient in next phase.";
    }

    @Override
    public Map<String, Object> buildLearnerProfileSummary(Long userId) {
        Map<String, Object> summary = new HashMap<>();
        summary.put("userId", userId);
        summary.put("status", "placeholder");
        summary.put("message", "Profile summary will be generated by Spring AI in next phase.");
        return summary;
    }
}
